service: cw-customers

stage: ${self:provider.stage}

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 30
  region: ${opt:region, 'ap-south-1'}

  environment: 
    STAGE: ${opt:stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:InvokeFunction
      Resource: 'arn:aws:dynamodb:ap-south-1:*:*'
    # - Effect: Allow
    #   Action:
    #     - lambda:InvokeFunction
    #     - lambda:Invoke        
    #   Resource: 'arn:aws:dynamodb:ap-south-1:*:*'

functions:
   getcustomerbyid:
    handler: handlers/getcustomerbyid.getcustomer
    events:
      - http:
          path: customerid/{cid}
          method: get
          cors: true

   createcustomer:
    handler: handlers/addcustomer.createcustomer
    enviroment:
      CREATE_CR_LAMBDA_ARN: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:cw-customers-${opt:stage}-createcustomerresources
    events:
      - http:
          path: customerid
          method: post
          cors: true
          
   createcustomerresources:
    handler: handlers/createcustomerresources.createcustomerresources

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customers-${opt:stage}
        AttributeDefinitions:
          - AttributeName: cid
            AttributeType: S
        KeySchema:
          - AttributeName: cid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    AdminCustomerResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: admin-customer-resources-${opt:stage}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CustomerResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customer-resources-${opt:stage}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S          
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
  
plugins:
  - serverless-pseudo-parameters