service: cw-customers

stage: ${self:provider.stage}

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 30
  region: ${opt:region, 'ap-south-1'}

  environment: 
    STAGE: ${opt:stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:CreateTable
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem        
      Resource: '*'
    - Effect: Allow
      Action:
        - lambda:Invoke
        - lambda:InvokeFunction
      Resource: '*'
    - Effect: Allow
      Action: 
        - cognito-idp:*
      Resource: '*'
    - Effect: Allow
      Action: 
        - sns:Publish
      Resource: '*'

functions:
   getcustomerbyid:
    handler: handlers/getcustomerbyid.getcustomer
    events:
      - http:
          path: customerid/{cid}
          method: get
          cors: true
  
   createcustomer:
    handler: handlers/addcustomer.createcustomer
    environment:
      CREATE_CR_LAMBDA_ARN: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:cw-customers-${opt:stage}-createcustomerresources
    events:
      - http:
          path: customerid
          method: post
          cors: true

   createcustomerresources:
    handler: handlers/createcustomerresources.createcustomerresources

   updatecustomer:
    handler: handlers/updatecustomer.updatecustomer
    events:
      - http:
          path: /{cuid}
          method: put
          cors: true

   admincustomerresources:
    handler: handlers/loaddata.customerresourcesdata

resources:
  Resources:
    SMSRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: Poonam1-SMS1-Role1
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - cognito-idp
                Action: sts:AssumeRole
        MaxSessionDuration: 3600
        Policies:
            - PolicyName: Cognito-1509099821021
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - "sns:publish"
                    Resource: "*"
        Description: SMS Role for SNS
        Path: /

    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customers-${opt:stage}
        AttributeDefinitions:
          - AttributeName: cid
            AttributeType: S
          - AttributeName: cuid
            AttributeType: S
        KeySchema:
          - AttributeName: cid
            KeyType: HASH
          - AttributeName: cuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    AdminCustomerResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: admin-customer-resources-${opt:stage}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CustomerResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customer-resources-${opt:stage}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S          
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
      
plugins:
  - serverless-pseudo-parameters
  - serverless-cognito-add-custom-attributes
