service: cw-customers

stage: ${self:provider.stage}

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 30
  region: ${opt:region, 'us-east-1'}

  environment: 
    STAGE: ${opt:stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Get*
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:CreateTable
        - dynamodb:Update*
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb::*:table/customer-${opt:stage}
    - Effect: Allow
      Action:
        - lambda:Invoke
      Resource: '*'



functions:
   getcustomerbyid:
    handler: handlers/getcustomerbyid.getcustomer
    events:
      - http:
          path: customerid/{cid}
          method: get
          cors: true

   createcustomer:
    handler: handlers/addcustomer.createcustomer
    enviroment:
      CREATE_CR_LAMBDA_ARN: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:cw-customers-${opt:stage}-createcustomerresources
    events:
      - http:
          path: customerid
          method: post
          cors: true
          
   createcustomerresources:
    handler: handlers/createcustomerresources.createcustomerresources
    events:
      - http:
          path: customerid/createcustomerresources
          method: post
          cors: true
 
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customer-${opt:stage}
        AttributeDefinitions:
          - AttributeName: cid
            AttributeType: S
        KeySchema:
          - AttributeName: cid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    AdminCustomerResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: admin-customer-resources-${opt:stage}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CustomerResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customer-resources-${opt:stage}
        AttributeDefinitions:
          - AttributeName: cuid
            AttributeType: S          
        KeySchema:
          - AttributeName: cuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
  
plugins:
  - serverless-pseudo-parameters